language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11.2
  - DJANGO_VERSION=1.11.3
  - DJANGO_VERSION=1.11
# https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - env: DJANGO_VERSION=1.9
      python: 3.6
    - env: DJANGO_VERSION=1.10
      python: 3.6
addons:
  apt_packages:
    - pandoc
before_install:
    - ./pypi_packager.sh
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -e .
  - pip install -q coveralls
script:
  - coverage run --source=echoices echoices/tests/__main__.py
after_success:
  - coveralls
